doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        url: 'mysql://b8d67caa8d95f4:53295322@us-cdbr-iron-east-05.cleardb.net/heroku_2dad42c0a402a1c?reconnect=true'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
